{"status": "broken", "description": "Activating the pick action test and checking whether it was successful.\n        ", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "complex_test"}, {"name": "subSuite", "value": "TestComplexScenario"}, {"name": "host", "value": "Hyper-Dock"}, {"name": "thread", "value": "12724-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython2"}, {"name": "package", "value": "tests.complex_test"}], "stop": 1608339711342, "uuid": "cab1dd39-d529-43b0-8df4-1f112c03e346", "historyId": "6df5cbf7c00ce5f14b4c42d69bcd2de9", "name": "test_verification_of_pick_action", "start": 1608339708792, "fullName": "tests.complex_test.TestComplexScenario#test_verification_of_pick_action", "statusDetails": {"message": "AttributeError: 'module' object has no attribute 'CollisionWorld'", "trace": "self = <tests.complex_test.TestComplexScenario instance at 0x7fed50f7aef0>\n\n    def test_verification_of_pick_action(self):\n        \"\"\"Activating the pick action test and checking whether it was successful.\n        \"\"\"\n        data_logger('logger/logs/pick_action_start')\n        # Pick from table and place on table\n        result = MoveItPickAndPlace(pick_x = -0.03, pick_y = 0.96 , pick_z = 0.57,\n>                                   place_x = 0.5, place_y = 1.0 , place_z = 0.6)\n\ntests/complex_test.py:173: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\npick_x = -0.03, pick_y = 0.96, pick_z = 0.57, place_x = 0.5, place_y = 1.0\nplace_z = 0.6\n\n    def MoveItPickAndPlace(pick_x = 0, pick_y = 0, pick_z = 0, place_x = 0, place_y = 0, place_z = 0):\n        # Prepare hsrb_interface\n        robot = hsrb_interface.Robot()\n        whole_body = robot.get(\"whole_body\")\n        omni_base = robot.get(\"omni_base\")\n    \n        gripper = robot.get(\"gripper\")\n    \n>       collision_world = hsrb_interface.CollisionWorld\nE       AttributeError: 'module' object has no attribute 'CollisionWorld'\n\ntests/action_client/experimental_pick_place_client.py:28: AttributeError"}, "attachments": [{"source": "dac548a3-6a04-4f8e-8d7e-c1141c816e1b-attachment.txt", "type": "text/plain", "name": "log"}, {"source": "f1eca89b-5dfe-4190-afd0-20130f942d1f-attachment.txt", "type": "text/plain", "name": "stdout"}, {"source": "737c15f8-23e3-4b12-9948-2a4676b89070-attachment.txt", "type": "text/plain", "name": "stderr"}]}