{"status": "broken", "description": "Activates perception action.\n        ", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "perceive_test"}, {"name": "subSuite", "value": "TestPerception"}, {"name": "host", "value": "Hyper-Dock"}, {"name": "thread", "value": "31299-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython2"}, {"name": "package", "value": "tests.perceive_test"}], "stop": 1608395136289, "uuid": "000ece94-60f3-468e-8140-00b1d326f802", "historyId": "5d9539f0f5eac3b37dd676d398f61a55", "name": "test_verification_of_perception", "start": 1608395136102, "fullName": "tests.perceive_test.TestPerception#test_verification_of_perception", "statusDetails": {"message": "NameError: global name 'result' is not defined", "trace": "self = <tests.perceive_test.TestPerception instance at 0x7f02e7a01f80>\n\n    def test_verification_of_perception(self):\n        \"\"\"Activates perception action.\n        \"\"\"\n        data_logger('logger/logs/perception')\n        # result = perceive_client()\n>       assert True == result\nE       NameError: global name 'result' is not defined\n\ntests/perceive_test.py:79: NameError"}, "attachments": [{"source": "e9916511-f913-477e-ae1f-7a4bbf7c59d3-attachment.txt", "type": "text/plain", "name": "log"}, {"source": "a068a15d-7b72-4224-a2e6-1f75ce2d2959-attachment.txt", "type": "text/plain", "name": "stdout"}, {"source": "774a6655-5ca6-4ae4-83fc-f4edb8fc1757-attachment.txt", "type": "text/plain", "name": "stderr"}]}