{"status": "broken", "description": "Activates perception action.\n        ", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "perceive_test"}, {"name": "subSuite", "value": "TestPerception"}, {"name": "host", "value": "Hyper-Dock"}, {"name": "thread", "value": "17500-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython2"}, {"name": "package", "value": "tests.perceive_test"}], "stop": 1608394410529, "uuid": "fcca8b90-d609-4b1a-8fcc-1184ee616e13", "historyId": "5d9539f0f5eac3b37dd676d398f61a55", "name": "test_verification_of_perception", "start": 1608394410429, "fullName": "tests.perceive_test.TestPerception#test_verification_of_perception", "statusDetails": {"message": "NameError: global name 'result' is not defined", "trace": "self = <tests.perceive_test.TestPerception instance at 0x7f30b5313908>\n\n    def test_verification_of_perception(self):\n        \"\"\"Activates perception action.\n        \"\"\"\n        data_logger('logger/logs/perception')\n        # result = perceive_client()\n>       assert True == result\nE       NameError: global name 'result' is not defined\n\ntests/perceive_test.py:78: NameError"}, "attachments": [{"source": "2daba59a-2ea9-4399-878f-031740f7c5c6-attachment.txt", "type": "text/plain", "name": "log"}, {"source": "69a04362-fb6b-4313-a530-7e63ed3ce45f-attachment.txt", "type": "text/plain", "name": "stdout"}, {"source": "87db0c48-d084-4234-9498-ff3da595de80-attachment.txt", "type": "text/plain", "name": "stderr"}]}