{"status": "broken", "description": "Activating the pick action test and checking whether it was successful.\n        ", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "complex_test"}, {"name": "subSuite", "value": "TestComplexScenario"}, {"name": "host", "value": "Hyper-Dock"}, {"name": "thread", "value": "849-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython2"}, {"name": "package", "value": "tests.complex_test"}], "stop": 1608375421065, "uuid": "0d8c4fb7-14be-45bb-9730-72b6e06ce97c", "historyId": "6df5cbf7c00ce5f14b4c42d69bcd2de9", "name": "test_verification_of_pick_action", "start": 1608375420892, "fullName": "tests.complex_test.TestComplexScenario#test_verification_of_pick_action", "statusDetails": {"message": "TypeError: __init__() got an unexpected keyword argument 'wait_for_servers'", "trace": "self = <tests.complex_test.TestComplexScenario instance at 0x7faa0e2c4290>\n\n    def test_verification_of_pick_action(self):\n        \"\"\"Activating the pick action test and checking whether it was successful.\n        \"\"\"\n        data_logger('logger/logs/pick_action_start')\n        attempt = 0\n        while attempt<15:\n            try:\n                result = MoveItPickAndPlace(pick_x = -0.03, pick_y = 0.96 , pick_z = 0.57,\n>                                           place_x = 0.5, place_y = 1.0 , place_z = 0.6)\n\ntests/complex_test.py:174: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <tests.action_client.pick_place_client.MoveItPickAndPlace object at 0x7faa0e547250>\npick_x = -0.03, pick_y = 0.96, pick_z = 0.57, place_x = 0.5, place_y = 1.0\nplace_z = 0.6, wait = 0.0\n\n    def __init__(self, pick_x = 0, pick_y = 0, pick_z = 0, place_x = 0, place_y = 0, place_z = 0,wait=0.0):\n        # initialize\n        # moveit_commander.roscpp_initialize(sys.argv)\n        # rospy.init_node(\"moveit_demo\", anonymous=True)\n    \n        self.reference_frame = \"odom\"\n>       arm = moveit_commander.MoveGroupCommander(\"arm\", wait_for_servers=0.0)\nE       TypeError: __init__() got an unexpected keyword argument 'wait_for_servers'\n\ntests/action_client/pick_place_client.py:27: TypeError"}, "attachments": [{"source": "383697a5-5887-44ed-a6ee-a506e6232c1c-attachment.txt", "type": "text/plain", "name": "log"}, {"source": "f0951cf2-44ec-4a7b-8b26-7040cc17d2cc-attachment.txt", "type": "text/plain", "name": "stdout"}, {"source": "161101c2-7cf7-4e3d-b951-2a74334044f0-attachment.txt", "type": "text/plain", "name": "stderr"}]}