[32mINFO    [0m rospy.internal:core.py:138 topic[/tf_static] adding connection to [http://192.168.0.101:40801/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] adding connection to [http://192.168.0.101:34059/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] adding connection to [http://192.168.0.101:33639/], count 1
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] adding connection to [http://192.168.0.101:42773/], count 1
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] adding connection to [http://192.168.0.101:45147/], count 1
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] adding connection to [http://192.168.0.101:40801/], count 1
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] adding connection to [http://192.168.0.101:45881/], count 1
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] adding connection to [http://192.168.0.101:34839/], count 2
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] adding connection to [http://192.168.0.101:35121/], count 1
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] adding connection to [http://192.168.0.101:36805/], count 4
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] adding connection to [http://192.168.0.101:37831/], count 4
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] adding connection to [http://192.168.0.101:37687/], count 7
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/arm_trajectory_controller/follow_joint_trajectory/status] adding connection to [http://192.168.0.101:37687/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/arm_trajectory_controller/follow_joint_trajectory/result] adding connection to [http://192.168.0.101:37687/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/arm_trajectory_controller/follow_joint_trajectory/feedback] adding connection to [http://192.168.0.101:37687/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/arm_trajectory_controller/follow_joint_trajectory/cancel] adding connection to [/gazebo], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/arm_trajectory_controller/follow_joint_trajectory/goal] adding connection to [/gazebo], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/head_trajectory_controller/follow_joint_trajectory/feedback] adding connection to [http://192.168.0.101:37687/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/head_trajectory_controller/follow_joint_trajectory/result] adding connection to [http://192.168.0.101:37687/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/head_trajectory_controller/follow_joint_trajectory/status] adding connection to [http://192.168.0.101:37687/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/head_trajectory_controller/follow_joint_trajectory/goal] adding connection to [/gazebo], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/head_trajectory_controller/follow_joint_trajectory/cancel] adding connection to [/gazebo], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/gripper_controller/follow_joint_trajectory/feedback] adding connection to [http://192.168.0.101:37687/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/gripper_controller/follow_joint_trajectory/result] adding connection to [http://192.168.0.101:37687/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/gripper_controller/follow_joint_trajectory/status] adding connection to [http://192.168.0.101:37687/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/gripper_controller/follow_joint_trajectory/cancel] adding connection to [/gazebo], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/gripper_controller/follow_joint_trajectory/goal] adding connection to [/gazebo], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/omni_base_controller/follow_joint_trajectory/status] adding connection to [http://192.168.0.101:37687/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/omni_base_controller/follow_joint_trajectory/result] adding connection to [http://192.168.0.101:37687/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/omni_base_controller/follow_joint_trajectory/feedback] adding connection to [http://192.168.0.101:37687/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/omni_base_controller/follow_joint_trajectory/goal] adding connection to [/gazebo], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/omni_base_controller/follow_joint_trajectory/cancel] adding connection to [/gazebo], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/impedance_control/follow_joint_trajectory/feedback] adding connection to [http://192.168.0.101:36441/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/impedance_control/follow_joint_trajectory/result] adding connection to [http://192.168.0.101:36441/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/impedance_control/follow_joint_trajectory/status] adding connection to [http://192.168.0.101:36441/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/impedance_control/follow_joint_trajectory/goal] adding connection to [/hsrb/impedance_control], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/impedance_control/follow_joint_trajectory/cancel] adding connection to [/hsrb/impedance_control], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/joint_states] adding connection to [http://192.168.0.101:37687/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/mdr_actions/perceive_plane_server/goal] adding connection to [/mdr_actions/perceive_plane_server], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/mdr_actions/perceive_plane_server/cancel] adding connection to [/mdr_actions/perceive_plane_server], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/mdr_actions/perceive_plane_server/feedback] adding connection to [http://192.168.0.101:39983/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/mdr_actions/perceive_plane_server/result] adding connection to [http://192.168.0.101:39983/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/mdr_actions/perceive_plane_server/status] adding connection to [http://192.168.0.101:39983/], count 0
[32mINFO    [0m rospy.core:core.py:454 signal_shutdown [shutdown]
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/omni_base_controller/follow_joint_trajectory/cancel] removing connection to /gazebo
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/omni_base_controller/follow_joint_trajectory/goal] removing connection to /gazebo
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/arm_trajectory_controller/follow_joint_trajectory/goal] removing connection to /gazebo
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/impedance_control/follow_joint_trajectory/goal] removing connection to /hsrb/impedance_control
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/gripper_controller/follow_joint_trajectory/goal] removing connection to /gazebo
[32mINFO    [0m rospy.internal:core.py:138 topic[/rosout] removing connection to /rosout
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/head_trajectory_controller/follow_joint_trajectory/cancel] removing connection to /gazebo
[32mINFO    [0m rospy.internal:core.py:138 topic[/mdr_actions/perceive_plane_server/cancel] removing connection to /mdr_actions/perceive_plane_server
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/arm_trajectory_controller/follow_joint_trajectory/cancel] removing connection to /gazebo
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/impedance_control/follow_joint_trajectory/cancel] removing connection to /hsrb/impedance_control
[32mINFO    [0m rospy.internal:core.py:138 topic[/mdr_actions/perceive_plane_server/goal] removing connection to /mdr_actions/perceive_plane_server
[32mINFO    [0m rospy.internal:core.py:138 topic[/move_base_server/cancel] removing connection to /move_base_server
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/head_trajectory_controller/follow_joint_trajectory/goal] removing connection to /gazebo
[32mINFO    [0m rospy.internal:core.py:138 topic[/move_base_server/goal] removing connection to /move_base_server
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/gripper_controller/follow_joint_trajectory/cancel] removing connection to /gazebo
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/gripper_controller/follow_joint_trajectory/status] removing connection to http://192.168.0.101:37687/
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/omni_base_controller/follow_joint_trajectory/result] removing connection to http://192.168.0.101:37687/
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/omni_base_controller/follow_joint_trajectory/feedback] removing connection to http://192.168.0.101:37687/
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] removing connection to http://192.168.0.101:34059/
[33mWARNING [0m rospy.internal:core.py:144 Unknown error initiating TCP/IP socket to 192.168.0.101:47631 (http://192.168.0.101:34059/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 559, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] removing connection to http://192.168.0.101:33639/
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] removing connection to http://192.168.0.101:45147/
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] removing connection to http://192.168.0.101:40801/
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] removing connection to http://192.168.0.101:42773/
[33mWARNING [0m rospy.internal:core.py:144 Unknown error initiating TCP/IP socket to 192.168.0.101:45031 (http://192.168.0.101:42773/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 559, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] removing connection to http://192.168.0.101:45881/
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] removing connection to http://192.168.0.101:34839/
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] removing connection to http://192.168.0.101:35121/
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] removing connection to http://192.168.0.101:36805/
[33mWARNING [0m rospy.internal:core.py:144 Unknown error initiating TCP/IP socket to 192.168.0.101:48165 (http://192.168.0.101:36805/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 559, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] removing connection to http://192.168.0.101:37831/
[33mWARNING [0m rospy.internal:core.py:144 Unknown error initiating TCP/IP socket to 192.168.0.101:37033 (http://192.168.0.101:37831/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 651, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[1m[31mERROR   [0m rospy.topics:topics.py:329 Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 839, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] removing connection to http://192.168.0.101:37687/
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/omni_base_controller/state] removing connection to http://192.168.0.101:37687/
[32mINFO    [0m rospy.internal:core.py:138 topic[/mdr_actions/perceive_plane_server/result] removing connection to http://192.168.0.101:39983/
[32mINFO    [0m rospy.internal:core.py:138 topic[/mdr_actions/perceive_plane_server/status] removing connection to http://192.168.0.101:39983/
[32mINFO    [0m rospy.internal:core.py:138 topic[/move_base_server/result] removing connection to http://192.168.0.101:35943/
[33mWARNING [0m rospy.internal:core.py:144 Unknown error initiating TCP/IP socket to 192.168.0.101:38899 (http://192.168.0.101:40801/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 556, in connect
    self.socket.connect((dest_addr, dest_port))
AttributeError: 'NoneType' object has no attribute 'connect'

[33mWARNING [0m rospy.internal:core.py:144 Unknown error initiating TCP/IP socket to 192.168.0.101:40895 (http://192.168.0.101:35943/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 559, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[32mINFO    [0m rospy.internal:core.py:138 topic[/tf_static] removing connection to http://192.168.0.101:40801/
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/arm_trajectory_controller/follow_joint_trajectory/feedback] removing connection to http://192.168.0.101:37687/
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/impedance_control/follow_joint_trajectory/feedback] removing connection to http://192.168.0.101:36441/
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/head_trajectory_controller/follow_joint_trajectory/status] removing connection to http://192.168.0.101:37687/
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/impedance_control/follow_joint_trajectory/status] removing connection to http://192.168.0.101:36441/
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/head_trajectory_controller/follow_joint_trajectory/feedback] removing connection to http://192.168.0.101:37687/
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/gripper_controller/follow_joint_trajectory/result] removing connection to http://192.168.0.101:37687/
[33mWARNING [0m rospy.internal:core.py:144 Unknown error initiating TCP/IP socket to 192.168.0.101:49127 (http://192.168.0.101:36441/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 559, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/omni_base_controller/follow_joint_trajectory/status] removing connection to http://192.168.0.101:37687/
[33mWARNING [0m rospy.internal:core.py:144 Unknown error initiating TCP/IP socket to 192.168.0.101:38937 (http://192.168.0.101:37687/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 651, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[1m[31mERROR   [0m rospy.topics:topics.py:329 Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 839, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/arm_trajectory_controller/follow_joint_trajectory/status] removing connection to http://192.168.0.101:37687/
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/gripper_controller/follow_joint_trajectory/feedback] removing connection to http://192.168.0.101:37687/
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/joint_states] removing connection to http://192.168.0.101:37687/
[33mWARNING [0m rospy.internal:core.py:144 Unknown error initiating TCP/IP socket to 192.168.0.101:40895 (http://192.168.0.101:35943/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 559, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[32mINFO    [0m rospy.internal:core.py:138 topic[/move_base_server/feedback] removing connection to http://192.168.0.101:35943/
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/head_trajectory_controller/follow_joint_trajectory/result] removing connection to http://192.168.0.101:37687/
[32mINFO    [0m rospy.internal:core.py:138 topic[/clock] removing connection to http://192.168.0.101:37687/
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/arm_trajectory_controller/follow_joint_trajectory/result] removing connection to http://192.168.0.101:37687/
[33mWARNING [0m rospy.internal:core.py:144 Unknown error initiating TCP/IP socket to 192.168.0.101:38937 (http://192.168.0.101:37687/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 559, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[32mINFO    [0m rospy.internal:core.py:138 topic[/mdr_actions/perceive_plane_server/feedback] removing connection to http://192.168.0.101:39983/
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/impedance_control/follow_joint_trajectory/result] removing connection to http://192.168.0.101:36441/
[32mINFO    [0m rospy.internal:core.py:138 topic[/move_base_server/status] removing connection to http://192.168.0.101:35943/
[32mINFO    [0m rospy.impl.masterslave:masterslave.py:342 shutdown
[33mWARNING [0m rospy.internal:core.py:144 Unknown error initiating TCP/IP socket to 192.168.0.101:38937 (http://192.168.0.101:37687/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 559, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[33mWARNING [0m rospy.internal:core.py:144 Unknown error initiating TCP/IP socket to 192.168.0.101:38937 (http://192.168.0.101:37687/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 559, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[33mWARNING [0m rospy.internal:core.py:144 Unknown error initiating TCP/IP socket to 192.168.0.101:38937 (http://192.168.0.101:37687/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 559, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[33mWARNING [0m rospy.internal:core.py:144 Unknown error initiating TCP/IP socket to 192.168.0.101:38937 (http://192.168.0.101:37687/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 559, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[33mWARNING [0m rospy.internal:core.py:144 Unknown error initiating TCP/IP socket to 192.168.0.101:38937 (http://192.168.0.101:37687/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 559, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[33mWARNING [0m rospy.internal:core.py:144 Unknown error initiating TCP/IP socket to 192.168.0.101:38937 (http://192.168.0.101:37687/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 559, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'